version: '3.4'
services:
  netbox:
    ports:
    - 8080:8080
    volumes:
    - /dockers/netbox-docker/config:/etc/netbox/config
    - /dockers/netbox-docker/media:/opt/netbox/netbox/media
    - /dockers/netbox-docker/reports:/opt/netbox/netbox/reports
    - /dockers/netbox-docker/netbox-scripts-files:/opt/netbox/netbox/scripts
    healthcheck:
      retries: 15
  netbox-worker:
    volumes:
    - /dockers/netbox-docker/config:/etc/netbox/config
    - /dockers/netbox-docker/media:/opt/netbox/netbox/media
    - /dockers/netbox-docker/reports:/opt/netbox/netbox/reports
    - /dockers/netbox-docker/netbox-scripts-files:/opt/netbox/netbox/scripts
  netbox-housekeeping:
    volumes:
    - /dockers/netbox-docker/config:/etc/netbox/config
    - /dockers/netbox-docker/media:/opt/netbox/netbox/media
    - /dockers/netbox-docker/reports:/opt/netbox/netbox/reports
    - /dockers/netbox-docker/netbox-scripts-files:/opt/netbox/netbox/scripts
